
import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  selectedLanguage: string;
  setSelectedLanguage: (language: string) => void;
  translate: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionaries
const translations: Record<string, Record<string, string>> = {
  en: {
    'forms.title': 'Government Forms',
    'forms.subtitle': 'Digital form filling made easy',
    'forms.bankAccount': 'Bank Account Opening Form',
    'forms.panCard': 'PAN Card Application Form',
    'forms.voterId': 'Voter ID Application Form',
    'forms.rti': 'RTI Application Form',
    'forms.unpaidSalary': 'Unpaid Salary Complaint',
    'forms.epf': 'EPF Grievance Form',
    'forms.consumer': 'Consumer Forum Complaint',
    'forms.grievance': 'Online Grievance Redressal Form',
    'forms.cyber': 'Cyber Crime Complaint',
    'forms.dowry': 'Dowry Harassment Representation',
    'forms.termination': 'Illegal Termination Complaint',
    'forms.domestic': 'Domestic Violence Incident Report',
    'forms.legal': 'Application for Legal Aid',
    'forms.pension': 'Pension Grievance Submission',
    'forms.traffic': 'Traffic Fine Dispute Letter',
    'forms.fir': 'FIR Drafting Assistance Form',
    'forms.divorce': 'Mutual Divorce First Motion Draft',
    'forms.partition': 'Partition Suit Draft',
    'forms.property': 'Property Dispute Affidavit Draft',
    'forms.nameChange': 'Name Change Affidavit Draft',
    'forms.address': 'Address Correction Support Letter',
    'forms.birth': 'Birth/Death Certificate Correction Form',
    'forms.aadhaar': 'Aadhaar/ID Correction Support Letter',
    'categories.banking': 'Banking & Financial',
    'categories.legal': 'Legal & RTI',
    'categories.civil': 'Civil & Property',
    'categories.identity': 'Identity & Documents',
    'language.select': 'Select Language',
    'language.hindi': 'हिन्दी',
    'language.bengali': 'বাংলা',
    'language.tamil': 'தমিழ்',
    'language.telugu': 'తెలుగు',
    'language.marathi': 'मराठी',
    'language.gujarati': 'ગુજરાતી',
    'search.placeholder': 'Search forms...',
    'button.back': 'Back to Forms',
    'button.previous': 'Previous',
    'button.next': 'Next',
    'button.submit': 'Submit Form',
    'button.download': 'Download PDF',
    'button.preview': 'Preview Form',
    'button.home': 'Home',
    'button.useVoice': 'Use Voice Input',
    'button.stopListening': 'Stop Listening',
    'button.uploadFile': 'Upload File',
    'software.name': 'Vaani Nyay',
    'form.subtitle': 'Election Commission of India (Form-8)',
    'step.label': 'Step',
    'section.label': 'SECTION',
    'of.label': 'of',
    'enter.label': 'Enter',
    'confirm.saveChanges': 'Save changes and return to preview?',
    
    // Questions
    'question.assemblyConstituencyNo': 'What is your Assembly Constituency Number?',
    'question.assemblyConstituencyName': 'What is the name of your Assembly Constituency?',
    'question.parliamentaryConstituencyNo': 'What is your Parliamentary Constituency Number?',
    'question.parliamentaryConstituencyName': 'What is the name of your Parliamentary Constituency?',
    'question.applicantName': 'What is your full name?',
    'question.epicNo': 'What is your EPIC (Voter ID) Number?',
    'question.aadhaarNumber': 'What is your Aadhaar Number?',
    'question.mobileNoSelf': 'What is your mobile number?',
    'question.mobileNoRelative': 'What is your relative\'s mobile number?',
    'question.emailSelf': 'What is your email address?',
    'question.emailRelative': 'What is your relative\'s email address?',
    'question.shiftingReason': 'What is the reason for shifting your residence?',
    'question.houseNo': 'What is your house/building/apartment number?',
    'question.streetArea': 'What is your street/area/locality/mohalla/road?',
    'question.townVillage': 'What is your town/village name?',
    'question.postOffice': 'What is your post office name?',
    'question.pinCode': 'What is your PIN code?',
    'question.tehsilTaluka': 'What is your tehsil/taluka/mandal name?',
    'question.district': 'What is your district name?',
    'question.stateUt': 'What is your state/UT name?',
    'question.otherDocument': 'Please specify any other document you want to attach',
    'question.applicationType': 'Please select your application type',
    'question.documentsAvailable': 'Please select the documents you have available',
    'question.uploadDocument': 'Upload supporting documents',
    
    // Examples
    'example.assemblyConstituencyNo': 'e.g., 123',
    'example.assemblyConstituencyName': 'e.g., Gandhi Nagar',
    'example.parliamentaryConstituencyNo': 'e.g., 45',
    'example.parliamentaryConstituencyName': 'e.g., Delhi Central',
    'example.applicantName': 'e.g., Raj Kumar Sharma',
    'example.epicNo': 'e.g., ABC1234567',
    'example.aadhaarNumber': 'e.g., 1234 5678 9012',
    'example.mobileNoSelf': 'e.g., 9876543210',
    'example.mobileNoRelative': 'e.g., 9876543210',
    'example.emailSelf': 'e.g., raj.sharma@gmail.com',
    'example.emailRelative': 'e.g., family@gmail.com',
    'example.shiftingReason': 'e.g., Job transfer, Marriage, etc.',
    'example.houseNo': 'e.g., A-123, Flat 405',
    'example.streetArea': 'e.g., Main Street, Sector 15',
    'example.townVillage': 'e.g., Delhi, Mumbai',
    'example.postOffice': 'e.g., Central Post Office',
    'example.pinCode': 'e.g., 110001',
    'example.tehsilTaluka': 'e.g., Central Delhi',
    'example.district': 'e.g., New Delhi',
    'example.stateUt': 'e.g., Delhi, Maharashtra',
    'example.otherDocument': 'e.g., Birth Certificate, Passport',
    
    // Application types
    'appType.shifting': 'Shifting of Residence',
    'appType.correction': 'Correction of Entries in Existing Electoral Roll',
    'appType.replacement': 'Issue of Replacement EPIC without correction',
    'appType.disability': 'Request for marking as Person with Disability',
    
    // Document types
    'doc.utility': 'Water/Electricity/Gas connection Bill for that address (atleast 1 year)',
    'doc.passbook': 'Current passbook of Nationalised/Scheduled Bank/Post Office',
    'doc.land': 'Revenue Department\'s Land Owning records including Kisan Bahi',
    'doc.rent': 'Registered Rent Lease Deed (In case of tenant)',
    'doc.aadhaar': 'Aadhaar Card',
    'doc.passport': 'Indian Passport',
    'doc.sale': 'Registered Sale Deed (In case of own house)',
    
    // Preview form labels
    'preview.to': 'To,',
    'preview.electoralOfficer': 'The Electoral Registration Officer,',
    'preview.assemblyConstituency': 'No. & Name of Assembly Constituency',
    'preview.parliamentaryConstituency': 'Or No. & Name of Parliamentary Constituency#',
    'preview.unionTerritory': '(# only for Union Territories not having Legislative Assembly)',
    'preview.applicantName': '(i) Name of the applicant',
    'preview.epicNo': 'EPIC No.',
    'preview.aadhaarDetails': 'Aadhaar Details :- (Please tick the appropriate box)',
    'preview.aadhaarNumber': 'Aadhaar Number',
    'preview.noAadhaar': 'I am not able to furnish my Aadhaar Number because I don\'t have Aadhaar Number.',
    'preview.mobileNoSelf': 'Mobile No. of Self (or)',
    'preview.mobileNoRelative': 'Mobile No. of Father/Mother/Any other relative (if available)',
    'preview.emailSelf': 'Email Id of Self (or)',
    'preview.emailRelative': 'Email Id of Father/Mother/Any other relative (if available)',
    'preview.applicationType': '(ii) I submit application for (Tick any one of the following)',
    'preview.presentAddress': 'Present Address',
    'preview.houseNo': 'House/Building/Apartment No.',
    'preview.streetArea': 'Street/Area/Locality/Mohalla/Road',
    'preview.townVillage': 'Town/Village',
    'preview.postOffice': 'Post Office',
    'preview.pinCode': 'PIN Code',
    'preview.tehsilTaluka': 'Tehsil/Taluka/Mandal',
    'preview.district': 'District',
    'preview.stateUt': 'State/UT',
    'preview.documents': 'Self-attested copy of address proof either in the name of applicant or anyone of the parents/spouse/adult child, if already enrolled with as elector at the same address (Attach any one of the documents mentioned below *):',
    'preview.otherDocument': 'Any Other:- (Pl. Specify)',
    'preview.edit': 'Edit'
  },
  hi: {
    'forms.title': 'सरकारी फॉर्म',
    'forms.subtitle': 'डिजिटल फॉर्म भरना आसान बनाया गया',
    'forms.bankAccount': 'बैंक खाता खोलने का फॉर्म',
    'forms.voterId': 'मतदाता पहचान पत्र आवेदन फॉर्म',
    'language.select': 'भाषा चुनें',
    'search.placeholder': 'फॉर्म खोजें...',
    'button.back': 'फॉर्म पर वापस जाएं',
    'button.previous': 'पिछला',
    'button.next': 'अगला',
    'button.submit': 'फॉर्म जमा करें',
    'button.download': 'पीडीएफ डाउनलोड करें',
    'button.preview': 'फॉर्म पूर्वावलोकन',
    'button.home': 'होम',
    'button.useVoice': 'आवाज़ इनपुट का उपयोग करें',
    'button.stopListening': 'सुनना बंद करें',
    'button.uploadFile': 'फ़ाइल अपलोड करें',
    'software.name': 'वाणी न्याय',
    'form.subtitle': 'भारत निर्वाचन आयोग (फॉर्म-8)',
    'step.label': 'चरण',
    'section.label': 'अनुभाग',
    'of.label': 'का',
    'enter.label': 'दर्ज करें',
    'confirm.saveChanges': 'परिवर्तन सहेजें और पूर्वावलोकन पर वापस जाएं?',
    
    // Questions in Hindi
    'question.assemblyConstituencyNo': 'आपका विधानसभा निर्वाचन क्षेत्र संख्या क्या है?',
    'question.assemblyConstituencyName': 'आपके विधानसभा निर्वाचन क्षेत्र का नाम क्या है?',
    'question.parliamentaryConstituencyNo': 'आपका संसदीय निर्वाचन क्षेत्र संख्या क्या है?',
    'question.parliamentaryConstituencyName': 'आपके संसदीय निर्वाचन क्षेत्र का नाम क्या है?',
    'question.applicantName': 'आपका पूरा नाम क्या है?',
    'question.epicNo': 'आपका EPIC (मतदाता पहचान पत्र) संख्या क्या है?',
    'question.aadhaarNumber': 'आपका आधार संख्या क्या है?',
    'question.mobileNoSelf': 'आपका मोबाइल नंबर क्या है?',
    'question.mobileNoRelative': 'आपके रिश्तेदार का मोबाइल नंबर क्या है?',
    'question.emailSelf': 'आपका ईमेल पता क्या है?',
    'question.emailRelative': 'आपके रिश्तेदार का ईमेल पता क्या है?',
    'question.shiftingReason': 'निवास स्थान बदलने का कारण क्या है?',
    'question.houseNo': 'आपका घर/भवन/अपार्टमेंट संख्या क्या है?',
    'question.streetArea': 'आपकी सड़क/क्षेत्र/मोहल्ला/सड़क का नाम क्या है?',
    'question.townVillage': 'आपके शहर/गाँव का नाम क्या है?',
    'question.postOffice': 'आपके डाकघर का नाम क्या है?',
    'question.pinCode': 'आपका पिन कोड क्या है?',
    'question.tehsilTaluka': 'आपकी तहसील/तालुका/मंडल का नाम क्या है?',
    'question.district': 'आपके जिले का नाम क्या है?',
    'question.stateUt': 'आपके राज्य/केंद्र शासित प्रदेश का नाम क्या है?',
    'question.otherDocument': 'कृपया कोई अन्य दस्तावेज़ निर्दिष्ट करें जिसे आप संलग्न करना चाहते हैं',
    'question.applicationType': 'कृपया अपना आवेदन प्रकार चुनें',
    'question.documentsAvailable': 'कृपया उपलब्ध दस्तावेज़ चुनें',
    'question.uploadDocument': 'सहायक दस्तावेज़ अपलोड करें',
    
    // Examples in Hindi
    'example.assemblyConstituencyNo': 'उदा., 123',
    'example.assemblyConstituencyName': 'उदा., गांधी नगर',
    'example.parliamentaryConstituencyNo': 'उदा., 45',
    'example.parliamentaryConstituencyName': 'उदा., दिल्ली केंद्रीय',
    'example.applicantName': 'उदा., राज कुमार शर्मा',
    'example.epicNo': 'उदा., ABC1234567',
    'example.aadhaarNumber': 'उदा., 1234 5678 9012',
    'example.mobileNoSelf': 'उदा., 9876543210',
    'example.mobileNoRelative': 'उदा., 9876543210',
    'example.emailSelf': 'उदा., raj.sharma@gmail.com',
    'example.emailRelative': 'उदा., family@gmail.com',
    'example.shiftingReason': 'उदा., नौकरी का स्थानांतरण, विवाह, आदि।',
    'example.houseNo': 'उदा., A-123, फ्लैट 405',
    'example.streetArea': 'उदा., मुख्य सड़क, सेक्टर 15',
    'example.townVillage': 'उदा., दिल्ली, मुंबई',
    'example.postOffice': 'उदा., केंद्रीय डाकघर',
    'example.pinCode': 'उदा., 110001',
    'example.tehsilTaluka': 'उदा., केंद्रीय दिल्ली',
    'example.district': 'उदा., नई दिल्ली',
    'example.stateUt': 'उदा., दिल्ली, महाराष्ट्र',
    'example.otherDocument': 'उदा., जन्म प्रमाण पत्र, पासपोर्ट',
    
    // Application types in Hindi
    'appType.shifting': 'निवास स्थान परिवर्तन',
    'appType.correction': 'मौजूदा मतदाता सूची में सुधार',
    'appType.replacement': 'बिना सुधार के प्रतिस्थापन EPIC जारी करना',
    'appType.disability': 'विकलांग व्यक्ति के रूप में चिह्नित करने का अनुरोध',
    
    // Document types in Hindi
    'doc.utility': 'उस पते के लिए पानी/बिजली/गैस कनेक्शन बिल (कम से कम 1 साल)',
    'doc.passbook': 'राष्ट्रीयकृत/अनुसूचित बैंक/पोस्ट ऑफिस की वर्तमान पासबुक',
    'doc.land': 'किसान बही सहित राजस्व विभाग के भूमि स्वामित्व रिकॉर्ड',
    'doc.rent': 'पंजीकृत किराया पट्टा विलेख (किरायेदार के मामले में)',
    'doc.aadhaar': 'आधार कार्ड',
    'doc.passport': 'भारतीय पासपोर्ट',
    'doc.sale': 'पंजीकृत बिक्री विलेख (अपने घर के मामले में)'
  },
  bn: {
    'forms.title': 'সরকারি ফর্ম',
    'forms.subtitle': 'ডিজিটাল ফর্ম পূরণ সহজ করা হয়েছে',
    'forms.bankAccount': 'ব্যাংক অ্যাকাউন্ট খোলার ফর্ম',
    'forms.voterId': 'ভোটার আইডি আবেদন ফর্ম',
    'language.select': 'ভাষা নির্বাচন করুন',
    'search.placeholder': 'ফর্ম খুঁজুন...',
    'button.back': 'ফর্মে ফিরে যান',
    'button.previous': 'পূর্ববর্তী',
    'button.next': 'পরবর্তী',
    'button.submit': 'ফর্ম জমা দিন',
    'button.download': 'পিডিএফ ডাউনলোড করুন',
    'button.preview': 'ফর্ম প্রিভিউ',
    'button.home': 'হোম',
    'button.useVoice': 'ভয়েস ইনপুট ব্যবহার করুন',
    'button.stopListening': 'শোনা বন্ধ করুন',
    'button.uploadFile': 'ফাইল আপলোড করুন',
    'software.name': 'বাণী ন্যায়',
    'form.subtitle': 'ভারতের নির্বাচন কমিশন (ফর্ম-৮)',
    'step.label': 'ধাপ',
    'section.label': 'বিভাগ',
    'of.label': 'এর',
    'enter.label': 'প্রবেশ করুন',
    'confirm.saveChanges': 'পরিবর্তন সংরক্ষণ করুন এবং প্রিভিউতে ফিরে যান?',
    
    // Questions in Bengali  
    'question.assemblyConstituencyNo': 'আপনার বিধানসভা নির্বাচনী এলাকার নম্বর কী?',
    'question.assemblyConstituencyName': 'আপনার বিধানসভা নির্বাচনী এলাকার নাম কী?',
    'question.parliamentaryConstituencyNo': 'আপনার সংসদীয় নির্বাচনী এলাকার নম্বর কী?',
    'question.parliamentaryConstituencyName': 'আপনার সংসদীয় নির্বাচনী এলাকার নাম কী?',
    'question.applicantName': 'আপনার পূর্ণ নাম কী?',
    'question.epicNo': 'আপনার EPIC (ভোটার আইডি) নম্বর কী?',
    'question.aadhaarNumber': 'আপনার আধার নম্বর কী?',
    'question.mobileNoSelf': 'আপনার মোবাইল নম্বর কী?',
    'question.mobileNoRelative': 'আপনার আত্মীয়ের মোবাইল নম্বর কী?',
    'question.emailSelf': 'আপনার ইমেইল ঠিকানা কী?',
    'question.emailRelative': 'আপনার আত্মীয়ের ইমেইল ঠিকানা কী?',
    'question.shiftingReason': 'বাসস্থান পরিবর্তনের কারণ কী?',
    'question.houseNo': 'আপনার বাড়ি/ভবন/অ্যাপার্টমেন্ট নম্বর কী?',
    'question.streetArea': 'আপনার রাস্তা/এলাকা/পাড়া/রোডের নাম কী?',
    'question.townVillage': 'আপনার শহর/গ্রামের নাম কী?',
    'question.postOffice': 'আপনার ডাকঘরের নাম কী?',
    'question.pinCode': 'আপনার পিন কোড কী?',
    'question.tehsilTaluka': 'আপনার তহসিল/তালুকা/মন্ডলের নাম কী?',
    'question.district': 'আপনার জেলার নাম কী?',
    'question.stateUt': 'আপনার রাজ্য/কেন্দ্রশাসিত অঞ্চলের নাম কী?',
    'question.otherDocument': 'আপনি যে অন্য কোনো নথি সংযুক্ত করতে চান তা উল্লেখ করুন',
    'question.applicationType': 'আপনার আবেদনের ধরন নির্বাচন করুন',
    'question.documentsAvailable': 'আপনার কাছে উপলব্ধ নথিগুলি নির্বাচন করুন',
    'question.uploadDocument': 'সহায়ক নথি আপলোড করুন'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [selectedLanguage, setSelectedLanguage] = useState('en');

  const translate = (key: string): string => {
    return translations[selectedLanguage]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ selectedLanguage, setSelectedLanguage, translate }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
